CREATE TABLE "NAVRECORDS" (
	"SCHEMECODE"	INTEGER NOT NULL,
	"ISIN_Div_Payout_ISIN_Growth"	TEXT,
	"ISIN_Div_Reinvestment"	TEXT,
	"NET_ASSET_VALUE"	REAL,
	"NAVDATE"	TEXT,
	PRIMARY KEY("SCHEMECODE","NAVDATE")
)