SELECT NAVRECORDS.ROWID, NAVRECORDS.SCHEMECODE, SCHEMES.SCHEMENAME, NAVRECORDS.NET_ASSET_VALUE, date(NAVRECORDS.NAVDATE) as NAVDATE 
	FROM NAVRECORDS
		
INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = NAVRECORDS.SCHEMECODE
--INNER JOIN SCHEME_TYPE ON SCHEME_TYPE.ROWID = SCHEMES.SCHEMETYPEID
--INNER JOIN FUNDHOUSE ON FUNDHOUSE.FUNDHOUSECODE = SCHEMES.FUNDHOUSECODE

WHERE 
-- FUNDHOUSE.FUNDHOUSECODE = 3 

-- AND SCHEME_TYPE.ID = 1 

NAVRECORDS.SCHEMECODE = 120465

AND 

NAVRECORDS.NAVDATE >= '2020-07-10' 
AND NAVRECORDS.NAVDATE <= '2020-07-27' ORDER BY NAVRECORDS.NAVDATE ASC