SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, strftime('%d-%m-%Y', PORTFOLIO.PURCHASE_DATE) AS PURCHASE_DATE, 
		PORTFOLIO.PURCHASE_NAV, PORTFOLIO.PURCHASE_UNITS, PORTFOLIO.VALUE_AT_COST
FROM SCHEMES
INNER JOIN PORTFOLIO ON SCHEMES.SCHEMECODE = PORTFOLIO.SCHEMECODE
WHERE PORTFOLIO.MASTER_ROWID = 2
ORDER BY PORTFOLIO.SCHEMECODE ASC, PORTFOLIO.PURCHASE_DATE DESC

SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, strftime('%d-%m-%Y', NAVRECORDS.NAVDATE) as NAVDate, NAVRECORDS.NET_ASSET_VALUE
from NAVRECORDS
INNER JOIN SCHEMES ON NAVRECORDS.SCHEMECODE = SCHEMES.SCHEMECODE
WHERE NAVRECORDS.SCHEMECODE = 103155 AND  NAVRECORDS.NAVDATE >= '2018-01-07' --strftime('%d-%m-%Y', '2018-07-01')
ORDER BY NAVRECORDS.NAVDATE ASC


SELECT SCHEMES.SCHEMECODE AS SCHEME_CODE, SCHEMES.SCHEMENAME AS SCHEME_NAME, NAVRECORDS.NET_ASSET_VALUE as NET_ASSET_VALUE, 
	strftime('%d-%m-%Y', NAVRECORDS.NAVDATE) as DATE from NAVRECORDS 
	INNER JOIN SCHEMES ON NAVRECORDS.SCHEMECODE = SCHEMES.SCHEMECODE 
	WHERE NAVRECORDS.SCHEMECODE = 100033 AND NAVRECORDS.NAVDATE >= '2018-01-01' 
ORDER BY NAVRECORDS.NAVDATE ASC
--------------------------Get each scheme with its first and last purchase date
SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, min(strftime('%d-%m-%Y', PORTFOLIO.PURCHASE_DATE)) as FirstPurchaseDate, 
		max(strftime('%d-%m-%Y', PORTFOLIO.PURCHASE_DATE)) as LastPurchaseDate, sum(PORTFOLIO.PURCHASE_UNITS) as SUMUNITS
		
		FROM PORTFOLIO
		INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = PORTFOLIO.SCHEMECODE
		WHERE PORTFOLIO.MASTER_ROWID = 2
		GROUP BY PORTFOLIO.SCHEMECODE
		ORDER BY PORTFOLIO.SCHEMECODE ASC, FirstPurchaseDate ASC
		
		
------------------------------get cumulative sum for each scheme
SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, strftime('%d-%m-%Y', t1.PURCHASE_DATE) as FirstPurchaseDate, 
		t1.PURCHASE_UNITS, sum(t2.PURCHASE_UNITS)
		FROM PORTFOLIO t1
		INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = t1.SCHEMECODE
		INNER join PORTFOLIO t2 on t1.PURCHASE_DATE >= t2.PURCHASE_DATE 
		WHERE t1.MASTER_ROWID = 2 and t1.SCHEMECODE = t2.SCHEMECODE
		GROUP BY t1.SCHEMECODE , t1.PURCHASE_DATE
		ORDER BY t1.SCHEMECODE ASC
		
------------------------------------trial 1 for combined navrecords + portfolio
SELECT PORTFOLIO.ROWID as PORTFOLIO_ROWID, FUNDHOUSE.NAME as MF_COMP_NAME, SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, NAVRECORDS.NET_ASSET_VALUE, strftime('%d-%m-%Y', NAVRECORDS.NAVDATE) as NAVDATE, 
strftime('%d-%m-%Y', PORTFOLIO.PURCHASE_DATE) as PurchaseDate, PORTFOLIO.PURCHASE_NAV, PORTFOLIO.PURCHASE_UNITS, PORTFOLIO.VALUE_AT_COST
from PORTFOLIO
INNER JOIN FUNDHOUSE ON FUNDHOUSE.FUNDHOUSECODE = SCHEMES.FUNDHOUSECODE 
INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = NAVRECORDS.SCHEMECODE
INNER join NAVRECORDS on PORTFOLIO.SCHEMECODE = NAVRECORDS.SCHEMECODE and NAVRECORDS.NAVDATE >= PORTFOLIO.PURCHASE_DATE
		WHERE PORTFOLIO.MASTER_ROWID = 2 
		ORDER BY PORTFOLIO.SCHEMECODE ASC,  PORTFOLIO.PURCHASE_DATE ASC --, NAVRECORDS.NAVDATE ASC

------------------------------------------------------------ trial query to get merged navrecord + portfolio. giving duplicate values from portfolio
SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, NAVRECORDS.NAVDATE, NAVRECORDS.NET_ASSET_VALUE, t1.PURCHASE_DATE, t1.PURCHASE_UNITS

from PORTFOLIO t1
INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = NAVRECORDS.SCHEMECODE
INNER join NAVRECORDS on t1.SCHEMECODE = NAVRECORDS.SCHEMECODE and NAVRECORDS.NAVDATE >= t1.PURCHASE_DATE
		WHERE t1.MASTER_ROWID = 2 
		ORDER BY t1.SCHEMECODE ASC,t1.PURCHASE_DATE ASC, NAVRECORDS.NAVDATE ASC

------------------------------------------------------
SELECT SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, NAVRECORDS.NAVDATE, NAVRECORDS.NET_ASSET_VALUE, PORTFOLIO.PURCHASE_DATE, PORTFOLIO.PURCHASE_UNITS

from NAVRECORDS, PORTFOLIO
INNER join SCHEMES on NAVRECORDS.SCHEMECODE = SCHEMES.SCHEMECODE
WHERE PORTFOLIO.MASTER_ROWID = 2 AND NAVRECORDS.NAVDATE >= (SELECT PORTFOLIO.PURCHASE_DATE FROM PORTFOLIO WHERE PORTFOLIO.SCHEMECODE = 103155)

		WHERE PORTFOLIO.MASTER_ROWID = 2 
		ORDER BY PORTFOLIO.SCHEMECODE ASC,PORTFOLIO.PURCHASE_DATE ASC, NAVRECORDS.NAVDATE ASC
