SELECT PORTFOLIO.ROWID AS ID, 
		FUNDHOUSE.NAME as FundHouse, 
		SCHEMES.SCHEMENAME as FundName, SCHEMES.SCHEMECODE as SCHEME_CODE, 
		strftime('%d-%m-%Y', PORTFOLIO.PURCHASE_DATE) AS PurchaseDate, PORTFOLIO.PURCHASE_NAV as PurchaseNAV, 
		PORTFOLIO.PURCHASE_UNITS as PurchaseUnits, PORTFOLIO.VALUE_AT_COST as ValueAtCost,
		NAVRECORDS.NET_ASSET_VALUE AS CurrentNAV, strftime('%d-%m-%Y', NAVRECORDS.NAVDATE) as NAVDate
				
		from SCHEMES
		INNER JOIN PORTFOLIO ON PORTFOLIO.SCHEMECODE = SCHEMES.SCHEMECODE
		INNER JOIN FUNDHOUSE ON FUNDHOUSE.FUNDHOUSECODE = SCHEMES.FUNDHOUSECODE
		INNER JOIN NAVRECORDS ON NAVRECORDS.SCHEMECODE = SCHEMES.SCHEMECODE
		
		WHERE NAVRECORDS.NAVDATE = SCHEMES.TO_DATE
