		
		SELECT NAVRECORDS.ID, SCHEME_TYPE.ID AS SCHEMETYPEID, SCHEME_TYPE.TYPE, FUNDHOUSE.FUNDHOUSECODE, FUNDHOUSE.NAME, 
			SCHEMES.SCHEMECODE, SCHEMES.SCHEMENAME, NAVRECORDS.NET_ASSET_VALUE, strftime('%d-%m-%Y', NAVRECORDS.NAVDATE) as NAVDATE FROM NAVRECORDS 
			INNER JOIN SCHEME_TYPE ON SCHEME_TYPE.ID = NAVRECORDS.SCHEMETYPEID 
			INNER JOIN FUNDHOUSE ON FUNDHOUSE.FUNDHOUSECODE = NAVRECORDS.FUNDHOUSECODE 
			INNER JOIN SCHEMES ON SCHEMES.SCHEMECODE = NAVRECORDS.SCHEMECODE 
			WHERE FUNDHOUSE.FUNDHOUSECODE = 53 
			AND SCHEMES.SCHEMECODE = 135122 
			AND date(NAVRECORDS.NAVDATE) >= date("2021-06-29") 
			AND date(NAVRECORDS.NAVDATE) <= date("2021-09-27") 