--DELETE FROM TRANSACTIONS;
--DELETE FROM NAVRECORDS;
--DELETE FROM SCHEMES;
--DELETE FROM SCHEME_TYPE;
--DELETE  FROM FUNDHOUSE;

INSERT INTO FUNDHOUSE(FUNDHOUSECODE, NAME) VALUES 
				("-1" , "ALL"),
	(39 , "ABN  AMRO Mutual Fund"),
	(3 , "Aditya Birla Sun Life Mutual Fund"),
	(50 , "AEGON Mutual Fund"),
	(1 , "Alliance Capital Mutual Fund"),
	(53 , "Axis Mutual Fund"),
	(4 , "Baroda Mutual Fund"),
	(36 , "Benchmark Mutual Fund"),
	(59 , "BNP Paribas Mutual Fund"),
	(46 , "BOI AXA Mutual Fund"),
	(32 , "Canara Robeco Mutual Fund"),
	(60 , "Daiwa Mutual Fund"),
	(31 , "DBS Chola Mutual Fund"),
	(38 , "Deutsche Mutual Fund"),
	(6 , "DSP Mutual Fund"),
	(47 , "Edelweiss Mutual Fund"),
	(40 , "Fidelity Mutual Fund"),
	(51 , "Fortis Mutual Fund"),
	(27 , "Franklin Templeton Mutual Fund"),
	(8 , "GIC Mutual Fund"),
	(49 , "Goldman Sachs Mutual Fund"),
	(9 , "HDFC Mutual Fund"),
	(37 , "HSBC Mutual Fund"),
	(20 , "ICICI Prudential Mutual Fund"),
	(57 , "IDBI Mutual Fund"),
	(48 , "IDFC Mutual Fund"),
	(68 , "IIFCL Mutual Fund (IDF)"),
	(62 , "IIFL Mutual Fund"),
	(11 , "IL&amp;F S Mutual Fund"),
	(65 , "IL&amp;FS Mutual Fund (IDF)"),
	(63 , "Indiabulls Mutual Fund"),
	(14 , "ING Mutual Fund"),

	(42 , "Invesco Mutual Fund"),
	(70 , "ITI Mutual Fund"),
	(16 , "JM Financial Mutual Fund"),
	(43 , "JPMorgan Mutual Fund"),
	(17 , "Kotak Mahindra Mutual Fund"),
	(56 , "L&amp;T Mutual Fund"),
	(18 , "LIC Mutual Fund"),
	(69 , "Mahindra Manulife Mutual Fund"),
	(45 , "Mirae Asset Mutual Fund"),
	(19 , "Morgan Stanley Mutual Fund"),
	(55 , "Motilal Oswal Mutual Fund"),
	(54 , "Navi Mutual Fund"),
	(21 , "Nippon India Mutual Fund"),
	(73 , "NJ Mutual Fund"),
	(58 , "PGIM India Mutual Fund"),
	(44 , "PineBridge Mutual Fund"),
	(34 , "PNB Mutual Fund"),
	(64 , "PPFAS Mutual Fund"),
	(10 , "Principal Mutual Fund"),
	(13 , "quant Mutual Fund"),
	(41 , "Quantum Mutual Fund"),
	(74 , "Samco Mutual Fund"),
	(22 , "SBI Mutual Fund"),
	(52 , "Shinsei Mutual Fund"),
	(67 , "Shriram Mutual Fund"),
	(2 , "Standard Chartered Mutual Fund"),
	(24 , "SUN F&amp;C Mutual Fund"),
	(33 , "Sundaram Mutual Fund"),
	(25 , "Tata Mutual Fund"),
	(26 , "Taurus Mutual Fund"),
	(72 , "Trust Mutual Fund"),
	(61 , "Union Mutual Fund"),
	(28 , "UTI Mutual Fund"),
	(71 , "YES Mutual Fund"),
	(29 , "Zurich India Mutual Fund");