SELECT SCHEME_TYPE.ROWID AS TYPEID, SCHEME_TYPE.TYPE, FUNDHOUSE.FUNDHOUSECODE, FUNDHOUSE.NAME, SCHEMES.SCHEMECODE, 
		SCHEMES.SCHEMENAME FROM SCHEMES 
		
		INNER JOIN SCHEME_TYPE ON SCHEMES.SCHEMETYPEID = SCHEME_TYPE.ROWID
		INNER JOIN FUNDHOUSE ON SCHEMES.FUNDHOUSECODE = FUNDHOUSE.FUNDHOUSECODE
		WHERE SCHEMES.FUNDHOUSECODE = 6
		AND SCHEME_TYPE.ROWID = 16