SELECT SCHEME_TYPE.ID AS SCHEMETYPEID, SCHEME_TYPE.TYPE, FUNDHOUSE.FUNDHOUSECODE, FUNDHOUSE.NAME, SCHEMES.SCHEMECODE, 
		SCHEMES.SCHEMENAME FROM SCHEMES INNER JOIN SCHEME_TYPE ON SCHEME_TYPE.ID = SCHEMES.SCHEMETYPEID INNER JOIN FUNDHOUSE ON FUNDHOUSE.FUNDHOUSECODE = SCHEMES.FUNDHOUSECODE 
			WHERE FUNDHOUSE.FUNDHOUSECODE = 6 